# TCL File Generated by Component Editor 15.0
# Tue Feb 13 20:06:29 PST 2018
# DO NOT MODIFY


# 
# new_component "new_component" v1.0
#  2018.02.13.20:06:29
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module new_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME new_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME new_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL signal_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file signal_control.sv SYSTEM_VERILOG PATH signal_control.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter idle STD_LOGIC_VECTOR 0
set_parameter_property idle DEFAULT_VALUE 0
set_parameter_property idle DISPLAY_NAME idle
set_parameter_property idle TYPE STD_LOGIC_VECTOR
set_parameter_property idle UNITS None
set_parameter_property idle ALLOWED_RANGES 0:63
set_parameter_property idle HDL_PARAMETER true
add_parameter writeVal STD_LOGIC_VECTOR 3
set_parameter_property writeVal DEFAULT_VALUE 3
set_parameter_property writeVal DISPLAY_NAME writeVal
set_parameter_property writeVal TYPE STD_LOGIC_VECTOR
set_parameter_property writeVal UNITS None
set_parameter_property writeVal ALLOWED_RANGES 0:63
set_parameter_property writeVal HDL_PARAMETER true
add_parameter writeVal_wait STD_LOGIC_VECTOR 5
set_parameter_property writeVal_wait DEFAULT_VALUE 5
set_parameter_property writeVal_wait DISPLAY_NAME writeVal_wait
set_parameter_property writeVal_wait TYPE STD_LOGIC_VECTOR
set_parameter_property writeVal_wait UNITS None
set_parameter_property writeVal_wait ALLOWED_RANGES 0:63
set_parameter_property writeVal_wait HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clock
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 0
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_writedata writedata Input 32
add_interface_port mm mm_address address Input 24
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_readdata readdata Output 32
add_interface_port mm mm_read read Input 1
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master write_master write Output 1
add_interface_port avalon_master wait_request waitrequest Input 1
add_interface_port avalon_master byteenable byteenable Output 4
add_interface_port avalon_master address_out address Output 32
add_interface_port avalon_master data_out writedata Output 32

