# TCL File Generated by Component Editor 15.0
# Mon Feb 12 19:22:38 PST 2018
# DO NOT MODIFY


# 
# pixel_cluster "Pixel_Cluster" v1.0
#  2018.02.12.19:22:38
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module pixel_cluster
# 
set_module_property DESCRIPTION ""
set_module_property NAME pixel_cluster
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Pixel_Cluster
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pixel_cluster
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pixel_cluster.sv SYSTEM_VERILOG PATH pixel_cluster/pixel_cluster.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N_REGS INTEGER 2
set_parameter_property N_REGS DEFAULT_VALUE 2
set_parameter_property N_REGS DISPLAY_NAME N_REGS
set_parameter_property N_REGS TYPE INTEGER
set_parameter_property N_REGS ENABLED false
set_parameter_property N_REGS UNITS None
set_parameter_property N_REGS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_REGS HDL_PARAMETER true
add_parameter ADDR_BITS INTEGER 4
set_parameter_property ADDR_BITS DEFAULT_VALUE 4
set_parameter_property ADDR_BITS DISPLAY_NAME ADDR_BITS
set_parameter_property ADDR_BITS TYPE INTEGER
set_parameter_property ADDR_BITS ENABLED false
set_parameter_property ADDR_BITS UNITS None
set_parameter_property ADDR_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_BITS HDL_PARAMETER true
add_parameter REG_BITS INTEGER 32
set_parameter_property REG_BITS DEFAULT_VALUE 32
set_parameter_property REG_BITS DISPLAY_NAME REG_BITS
set_parameter_property REG_BITS TYPE INTEGER
set_parameter_property REG_BITS ENABLED false
set_parameter_property REG_BITS UNITS None
set_parameter_property REG_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clock
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 0
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Input ADDR_BITS
add_interface_port mm mm_byteenable byteenable Input REG_BITS/8
add_interface_port mm mm_read read Input 1
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_readdata readdata Output REG_BITS
add_interface_port mm mm_writedata writedata Input REG_BITS
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point led_out
# 
add_interface led_out conduit end
set_interface_property led_out associatedClock clock
set_interface_property led_out associatedReset reset
set_interface_property led_out ENABLED true
set_interface_property led_out EXPORT_OF ""
set_interface_property led_out PORT_NAME_MAP ""
set_interface_property led_out CMSIS_SVD_VARIABLES ""
set_interface_property led_out SVD_ADDRESS_GROUP ""

add_interface_port led_out leds leds Output 10

