# TCL File Generated by Component Editor 15.0
# Thu Feb 15 14:17:01 PST 2018
# DO NOT MODIFY


# 
# pixel_cluster "Pixel_Cluster" v1.0
#  2018.02.15.14:17:01
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module pixel_cluster
# 
set_module_property DESCRIPTION ""
set_module_property NAME pixel_cluster
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Pixel_Cluster
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pixel_cluster
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pixel_cluster.sv SYSTEM_VERILOG PATH pixel_cluster/pixel_cluster.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N_REGS INTEGER 11 ""
set_parameter_property N_REGS DEFAULT_VALUE 11
set_parameter_property N_REGS DISPLAY_NAME N_REGS
set_parameter_property N_REGS TYPE INTEGER
set_parameter_property N_REGS UNITS None
set_parameter_property N_REGS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_REGS DESCRIPTION ""
set_parameter_property N_REGS HDL_PARAMETER true
add_parameter ADDR_BITS INTEGER 4
set_parameter_property ADDR_BITS DEFAULT_VALUE 4
set_parameter_property ADDR_BITS DISPLAY_NAME ADDR_BITS
set_parameter_property ADDR_BITS TYPE INTEGER
set_parameter_property ADDR_BITS ENABLED false
set_parameter_property ADDR_BITS UNITS None
set_parameter_property ADDR_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_BITS HDL_PARAMETER true
add_parameter REG_BITS INTEGER 32
set_parameter_property REG_BITS DEFAULT_VALUE 32
set_parameter_property REG_BITS DISPLAY_NAME REG_BITS
set_parameter_property REG_BITS TYPE INTEGER
set_parameter_property REG_BITS ENABLED false
set_parameter_property REG_BITS UNITS None
set_parameter_property REG_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG_BITS HDL_PARAMETER true
add_parameter N_COLORS INTEGER 3
set_parameter_property N_COLORS DEFAULT_VALUE 3
set_parameter_property N_COLORS DISPLAY_NAME N_COLORS
set_parameter_property N_COLORS TYPE INTEGER
set_parameter_property N_COLORS ENABLED false
set_parameter_property N_COLORS UNITS None
set_parameter_property N_COLORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_COLORS HDL_PARAMETER true
add_parameter COLOR_BITS INTEGER 8
set_parameter_property COLOR_BITS DEFAULT_VALUE 8
set_parameter_property COLOR_BITS DISPLAY_NAME COLOR_BITS
set_parameter_property COLOR_BITS TYPE INTEGER
set_parameter_property COLOR_BITS ENABLED false
set_parameter_property COLOR_BITS UNITS None
set_parameter_property COLOR_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLOR_BITS HDL_PARAMETER true
add_parameter X_MAX INTEGER 320
set_parameter_property X_MAX DEFAULT_VALUE 320
set_parameter_property X_MAX DISPLAY_NAME X_MAX
set_parameter_property X_MAX TYPE INTEGER
set_parameter_property X_MAX ENABLED false
set_parameter_property X_MAX UNITS None
set_parameter_property X_MAX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property X_MAX HDL_PARAMETER true
add_parameter Y_MAX INTEGER 240
set_parameter_property Y_MAX DEFAULT_VALUE 240
set_parameter_property Y_MAX DISPLAY_NAME Y_MAX
set_parameter_property Y_MAX TYPE INTEGER
set_parameter_property Y_MAX ENABLED false
set_parameter_property Y_MAX UNITS None
set_parameter_property Y_MAX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property Y_MAX HDL_PARAMETER true
add_parameter N_CLUSTERS INTEGER 4
set_parameter_property N_CLUSTERS DEFAULT_VALUE 4
set_parameter_property N_CLUSTERS DISPLAY_NAME N_CLUSTERS
set_parameter_property N_CLUSTERS TYPE INTEGER
set_parameter_property N_CLUSTERS ENABLED false
set_parameter_property N_CLUSTERS UNITS None
set_parameter_property N_CLUSTERS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_CLUSTERS HDL_PARAMETER true
add_parameter X_Y_BITS INTEGER 16
set_parameter_property X_Y_BITS DEFAULT_VALUE 16
set_parameter_property X_Y_BITS DISPLAY_NAME X_Y_BITS
set_parameter_property X_Y_BITS TYPE INTEGER
set_parameter_property X_Y_BITS ENABLED false
set_parameter_property X_Y_BITS UNITS None
set_parameter_property X_Y_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property X_Y_BITS HDL_PARAMETER true
add_parameter COUNTER_BITS INTEGER 16
set_parameter_property COUNTER_BITS DEFAULT_VALUE 16
set_parameter_property COUNTER_BITS DISPLAY_NAME COUNTER_BITS
set_parameter_property COUNTER_BITS TYPE INTEGER
set_parameter_property COUNTER_BITS ENABLED false
set_parameter_property COUNTER_BITS UNITS None
set_parameter_property COUNTER_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COUNTER_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clock
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 0
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Input ADDR_BITS
add_interface_port mm mm_byteenable byteenable Input REG_BITS/8
add_interface_port mm mm_read read Input 1
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_readdata readdata Output REG_BITS
add_interface_port mm mm_writedata writedata Input REG_BITS
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point frame_complete_irq
# 
add_interface frame_complete_irq interrupt end
set_interface_property frame_complete_irq associatedAddressablePoint mm
set_interface_property frame_complete_irq associatedClock clock
set_interface_property frame_complete_irq associatedReset reset
set_interface_property frame_complete_irq bridgedReceiverOffset ""
set_interface_property frame_complete_irq bridgesToReceiver ""
set_interface_property frame_complete_irq ENABLED true
set_interface_property frame_complete_irq EXPORT_OF ""
set_interface_property frame_complete_irq PORT_NAME_MAP ""
set_interface_property frame_complete_irq CMSIS_SVD_VARIABLES ""
set_interface_property frame_complete_irq SVD_ADDRESS_GROUP ""

add_interface_port frame_complete_irq irq_send_irq irq Output 1


# 
# connection point video_in
# 
add_interface video_in avalon_streaming end
set_interface_property video_in associatedClock clock
set_interface_property video_in associatedReset reset
set_interface_property video_in dataBitsPerSymbol 8
set_interface_property video_in errorDescriptor ""
set_interface_property video_in firstSymbolInHighOrderBits true
set_interface_property video_in maxChannel 0
set_interface_property video_in readyLatency 0
set_interface_property video_in ENABLED true
set_interface_property video_in EXPORT_OF ""
set_interface_property video_in PORT_NAME_MAP ""
set_interface_property video_in CMSIS_SVD_VARIABLES ""
set_interface_property video_in SVD_ADDRESS_GROUP ""

add_interface_port video_in st_ready ready Output 1
add_interface_port video_in st_startofpacket startofpacket Input 1
add_interface_port video_in st_endofpacket endofpacket Input 1
add_interface_port video_in st_valid valid Input 1
add_interface_port video_in st_data data Input COLOR_BITS*N_COLORS

