#ifndef ARM_SYSTEM_H
#define ARM_SYSTEM_H

// Base Address of the AXI Slaves in ARM
#define QSYS_AXI_BASE 0xC0000000

// Memory Mapped Reset Controller
#define MM_RESET_BASE (QSYS_AXI_BASE+0x300000)
#define MM_RESET_SPAN 0x10
// Resets Connected to the Reset Controller
#define MM_RESET_DRAW_DMA_CONTROLLER 0
#define MM_RESET_NIOS2 2

// UARTs, no need to use these, just use the drivers
#define TOUCHSCREEN_UART_BASE (QSYS_AXI_BASE+0x100000)
#define TOUCHSCREEN_UART_SPAN 0x20

#define VIDEO_UART_BASE (QSYS_AXI_BASE+0x101000)
#define VIDEO_UART_SPAN 0x20

#define WIFI_UART_BASE (QSYS_AXI_BASE+0x102000)
#define WIFI_UART_SPAN 0x20

#define UART_4_BASE (QSYS_AXI_BASE+0x103000)
#define UART_4_SPAN 0x20

// HPS to NIOS FIFO
#define HPS_NIOS_FIFO_BASE (QSYS_AXI_BASE+0x104000)
#define HPS_NIOS_FIFO_SPAN 0x4
#define HPS_NIOS_FIFO_STATUS_BASE (QSYS_AXI_BASE+0x104020)
#define HPS_NIOS_FIFO_STATUS_SPAN 0x20

// NIOS to HPS FIFO
#define NIOS_HPS_FIFO_BASE (QSYS_AXI_BASE+0x104100)
#define NIOS_HPS_FIFO_SPAN 0x4
#define NIOS_HPS_FIFO_STATUS_BASE (QSYS_AXI_BASE+0x104120)
#define NIOS_HPS_FIFO_STATUS_SPAN 0x20

// Graphics Controller
#define GRAPHICS_CONTROLLER_BASE (QSYS_AXI_BASE+0x4000000)
#define GRAPHICS_CONTROLLER_SPAN 0x4000000

// Draw DMA Controller
#define DRAW_DMA_CONTROLLER_BASE (QSYS_AXI_BASE+0x200000)
#define DRAW_DMA_CONTROLLER_SPAN 0x10

// Camera Video Frame Buffer
#define VIDEO_FRAMEBUFFER_BASE (QSYS_AXI_BASE+0x0)
#define VIDEO_FRAMEBUFFER_SPAN 0x4B000

// NIOS SDRAM
#define SDRAM_BASE (QSYS_AXI_BASE+0x08000000)
#define SDRAM_SPAN 0x4000000
#define SDRAM_FILE "nios.dat"

#endif // ARM_SYSTEM_H
