// cpen391_group5_qsys_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.0 153

`timescale 1 ps / 1 ps
module cpen391_group5_qsys_mm_interconnect_2 (
		input  wire        clocks_sys_clk_clk,                         //                       clocks_sys_clk.clk
		input  wire        Draw_DMA_reset_reset_bridge_in_reset_reset, // Draw_DMA_reset_reset_bridge_in_reset.reset
		input  wire [31:0] Draw_DMA_avalon_dma_master_address,         //           Draw_DMA_avalon_dma_master.address
		output wire        Draw_DMA_avalon_dma_master_waitrequest,     //                                     .waitrequest
		input  wire        Draw_DMA_avalon_dma_master_read,            //                                     .read
		output wire [31:0] Draw_DMA_avalon_dma_master_readdata,        //                                     .readdata
		output wire        Draw_DMA_avalon_dma_master_readdatavalid,   //                                     .readdatavalid
		input  wire        Draw_DMA_avalon_dma_master_lock,            //                                     .lock
		output wire [14:0] Draw_Buffer_s2_address,                     //                       Draw_Buffer_s2.address
		output wire        Draw_Buffer_s2_write,                       //                                     .write
		input  wire [31:0] Draw_Buffer_s2_readdata,                    //                                     .readdata
		output wire [31:0] Draw_Buffer_s2_writedata,                   //                                     .writedata
		output wire [3:0]  Draw_Buffer_s2_byteenable,                  //                                     .byteenable
		output wire        Draw_Buffer_s2_chipselect,                  //                                     .chipselect
		output wire        Draw_Buffer_s2_clken                        //                                     .clken
	);

	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_waitrequest;   // Draw_Buffer_s2_translator:uav_waitrequest -> Draw_DMA_avalon_dma_master_translator:uav_waitrequest
	wire  [31:0] draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdata;      // Draw_Buffer_s2_translator:uav_readdata -> Draw_DMA_avalon_dma_master_translator:uav_readdata
	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_debugaccess;   // Draw_DMA_avalon_dma_master_translator:uav_debugaccess -> Draw_Buffer_s2_translator:uav_debugaccess
	wire  [31:0] draw_dma_avalon_dma_master_translator_avalon_universal_master_0_address;       // Draw_DMA_avalon_dma_master_translator:uav_address -> Draw_Buffer_s2_translator:uav_address
	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_read;          // Draw_DMA_avalon_dma_master_translator:uav_read -> Draw_Buffer_s2_translator:uav_read
	wire   [3:0] draw_dma_avalon_dma_master_translator_avalon_universal_master_0_byteenable;    // Draw_DMA_avalon_dma_master_translator:uav_byteenable -> Draw_Buffer_s2_translator:uav_byteenable
	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid; // Draw_Buffer_s2_translator:uav_readdatavalid -> Draw_DMA_avalon_dma_master_translator:uav_readdatavalid
	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_lock;          // Draw_DMA_avalon_dma_master_translator:uav_lock -> Draw_Buffer_s2_translator:uav_lock
	wire         draw_dma_avalon_dma_master_translator_avalon_universal_master_0_write;         // Draw_DMA_avalon_dma_master_translator:uav_write -> Draw_Buffer_s2_translator:uav_write
	wire  [31:0] draw_dma_avalon_dma_master_translator_avalon_universal_master_0_writedata;     // Draw_DMA_avalon_dma_master_translator:uav_writedata -> Draw_Buffer_s2_translator:uav_writedata
	wire   [2:0] draw_dma_avalon_dma_master_translator_avalon_universal_master_0_burstcount;    // Draw_DMA_avalon_dma_master_translator:uav_burstcount -> Draw_Buffer_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) draw_dma_avalon_dma_master_translator (
		.clk                    (clocks_sys_clk_clk),                                                            //                       clk.clk
		.reset                  (Draw_DMA_reset_reset_bridge_in_reset_reset),                                    //                     reset.reset
		.uav_address            (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (Draw_DMA_avalon_dma_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (Draw_DMA_avalon_dma_master_waitrequest),                                        //                          .waitrequest
		.av_read                (Draw_DMA_avalon_dma_master_read),                                               //                          .read
		.av_readdata            (Draw_DMA_avalon_dma_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (Draw_DMA_avalon_dma_master_readdatavalid),                                      //                          .readdatavalid
		.av_lock                (Draw_DMA_avalon_dma_master_lock),                                               //                          .lock
		.av_burstcount          (1'b1),                                                                          //               (terminated)
		.av_byteenable          (4'b1111),                                                                       //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                          //               (terminated)
		.av_write               (1'b0),                                                                          //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                         //               (terminated)
		.av_response            (),                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (15),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) draw_buffer_s2_translator (
		.clk                    (clocks_sys_clk_clk),                                                            //                      clk.clk
		.reset                  (Draw_DMA_reset_reset_bridge_in_reset_reset),                                    //                    reset.reset
		.uav_address            (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (draw_dma_avalon_dma_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (Draw_Buffer_s2_address),                                                        //      avalon_anti_slave_0.address
		.av_write               (Draw_Buffer_s2_write),                                                          //                         .write
		.av_readdata            (Draw_Buffer_s2_readdata),                                                       //                         .readdata
		.av_writedata           (Draw_Buffer_s2_writedata),                                                      //                         .writedata
		.av_byteenable          (Draw_Buffer_s2_byteenable),                                                     //                         .byteenable
		.av_chipselect          (Draw_Buffer_s2_chipselect),                                                     //                         .chipselect
		.av_clken               (Draw_Buffer_s2_clken),                                                          //                         .clken
		.av_read                (),                                                                              //              (terminated)
		.av_begintransfer       (),                                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                                              //              (terminated)
		.av_burstcount          (),                                                                              //              (terminated)
		.av_readdatavalid       (1'b0),                                                                          //              (terminated)
		.av_waitrequest         (1'b0),                                                                          //              (terminated)
		.av_writebyteenable     (),                                                                              //              (terminated)
		.av_lock                (),                                                                              //              (terminated)
		.uav_clken              (1'b0),                                                                          //              (terminated)
		.av_debugaccess         (),                                                                              //              (terminated)
		.av_outputenable        (),                                                                              //              (terminated)
		.uav_response           (),                                                                              //              (terminated)
		.av_response            (2'b00),                                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                           //              (terminated)
	);

endmodule
